In [1]:
import numpy as np

## DataTypes and Attributes

In [6]:
# NumPy's mian datatype is ndarray
arr1 = np.array([1,2,3])
type(arr1)

numpy.ndarray

In [7]:
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3])

In [8]:
# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

In [9]:
# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [10]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [15]:
# Creaet a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Arrays

In [19]:
ones = np.ones((2,3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
zeros = np.zeros((2,3), dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [54]:
#cat_arr = np.full(shape=(3,5), fill_value="cat")
cat_arr = np.full((3,5), "cat")

In [56]:
cat_arr

array([['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat']], dtype='<U3')

In [21]:
range_arr = np.arange(0,20,2)
range_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
random_arr = np.random.randint(5, size=(2,4))
random_arr

array([[1, 0, 2, 4],
       [2, 1, 3, 3]], dtype=int32)

In [24]:
random_arr.size, random_arr.shape, random_arr.dtype

(8, (2, 4), dtype('int32'))

In [25]:
random_arr_2 = np.random.rand(5,3)
random_arr_2

array([[0.47670058, 0.14845525, 0.12434538],
       [0.10887288, 0.92314476, 0.5378325 ],
       [0.23508724, 0.51107192, 0.7929134 ],
       [0.40728728, 0.16755761, 0.06743505],
       [0.83110781, 0.75900358, 0.33110499]])

In [28]:
np.random.seed(3)
ra_1 = np.random.randint(10, size=(3,5))
ra_1

array([[8, 9, 3, 8, 8],
       [0, 5, 3, 9, 9],
       [5, 7, 6, 0, 4]], dtype=int32)

In [29]:
np.random.seed(3)
ra_2 = np.random.randint(10, size=(3,5))
ra_2

array([[8, 9, 3, 8, 8],
       [0, 5, 3, 9, 9],
       [5, 7, 6, 0, 4]], dtype=int32)

## Viewing arrays and matrices

In [30]:
np.unique(ra_2)

array([0, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [32]:
ra_3 = np.random.randint(10, size=(2, 3, 5, 6))
ra_3

array([[[[5, 3, 7, 2, 6, 1],
         [5, 8, 6, 8, 9, 5],
         [2, 1, 3, 8, 3, 7],
         [7, 6, 2, 5, 5, 8],
         [4, 1, 1, 1, 3, 2]],

        [[4, 7, 5, 6, 3, 3],
         [8, 0, 0, 5, 6, 4],
         [2, 1, 7, 5, 6, 8],
         [6, 9, 0, 9, 6, 7],
         [1, 6, 7, 7, 8, 0]],

        [[7, 5, 2, 9, 4, 1],
         [6, 5, 1, 9, 6, 2],
         [7, 9, 3, 0, 3, 0],
         [8, 9, 6, 0, 2, 7],
         [7, 7, 8, 0, 1, 8]]],


       [[[2, 3, 0, 7, 0, 7],
         [2, 0, 7, 8, 6, 6],
         [9, 9, 6, 9, 7, 1],
         [8, 6, 3, 0, 8, 1],
         [7, 9, 2, 5, 7, 1]],

        [[4, 1, 4, 5, 7, 7],
         [6, 8, 0, 9, 0, 0],
         [2, 3, 4, 3, 3, 1],
         [2, 6, 9, 9, 6, 3],
         [2, 1, 4, 2, 3, 0]],

        [[1, 1, 2, 7, 0, 6],
         [3, 4, 7, 3, 9, 4],
         [8, 0, 0, 8, 1, 1],
         [1, 8, 5, 0, 6, 5],
         [6, 1, 1, 0, 6, 3]]]], dtype=int32)

In [36]:
ra_3[:1,:,:2,:3]

array([[[[5, 3, 7],
         [5, 8, 6]],

        [[4, 7, 5],
         [8, 0, 0]],

        [[7, 5, 2],
         [6, 5, 1]]]], dtype=int32)

In [37]:
ra_4 = np.random.randint(100, size=(2,2,2,3,3,4))
ra_4

array([[[[[[18, 60, 18, 62],
           [98,  2, 49, 46],
           [21,  4, 27, 38]],

          [[78, 66, 23, 48],
           [84, 26, 56, 40],
           [85, 40,  9, 76]],

          [[28, 49,  9, 37],
           [ 9, 91, 39, 24],
           [11, 14,  9, 79]]],


         [[[40, 26, 73, 41],
           [49, 28, 39, 19],
           [26, 57, 85, 91]],

          [[40, 78, 38, 86],
           [77, 87, 99, 62],
           [ 4, 49, 56,  1]],

          [[74, 86, 71, 34],
           [ 0, 87, 45, 82],
           [95,  2,  3, 95]]]],



        [[[[52, 78, 36, 43],
           [38, 52, 25, 30],
           [19, 98, 52, 67]],

          [[46, 95, 35, 45],
           [28, 36, 55, 18],
           [67, 54, 99, 78]],

          [[64, 34, 82, 53],
           [24, 85, 71,  7],
           [47, 89, 26,  2]]],


         [[[70, 23, 80, 78],
           [14,  0, 35, 58],
           [33, 70, 69, 46]],

          [[32, 61, 10, 15],
           [74, 72, 97, 35],
           [ 4, 79, 47, 11]],

          [[6

In [63]:
ra_5 = np.array([10, 20, 30, 40, 50])
ra_5[[0, 1, 0, 1]]

array([10, 20, 10, 20])

## Manipulating arrays

In [39]:
a1

array([1, 2, 3])

In [40]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [49]:
a1 + ones

array([[2, 3, 4],
       [2, 3, 4]])

In [44]:
a1 - ones

array([[0, 1, 2],
       [0, 1, 2]])

In [64]:
np.sum(a1)

np.int64(6)

In [65]:
massive_array = np.random.random(999999)

In [66]:
massive_array[:20]

array([4.57606282e-01, 8.82129970e-01, 9.25518755e-01, 4.15462081e-02,
       1.58730726e-01, 6.19021814e-01, 2.60643022e-01, 6.25897789e-01,
       4.37958297e-01, 4.20755125e-01, 2.40102418e-02, 9.80847714e-01,
       1.21534586e-02, 2.74054429e-01, 1.80420438e-01, 5.19221434e-01,
       3.95464056e-04, 2.15496688e-01, 4.39012050e-01, 9.47794362e-01])

In [68]:
massive_array.size

999999

In [69]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

52.5 ms ± 455 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
260 μs ± 2.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [70]:
ra_5

array([10, 20, 30, 40, 50])

In [71]:
np.mean(ra_5)

np.float64(30.0)

In [72]:
np.min(ra_5)

np.int64(10)

In [73]:
np.std(ra_5)

np.float64(14.142135623730951)

In [74]:
np.var(ra_5)

np.float64(200.0)

In [80]:
a1 * ra_1

ValueError: operands could not be broadcast together with shapes (3,) (3,5) 

In [82]:
a1_reshape = a1.reshape(3, 1)

In [83]:
a1_reshape.shape

(3, 1)

In [84]:
a1_reshape

array([[1],
       [2],
       [3]])

In [86]:
ra_1

array([[8, 9, 3, 8, 8],
       [0, 5, 3, 9, 9],
       [5, 7, 6, 0, 4]], dtype=int32)

In [85]:
a1_reshape * ra_1

array([[ 8,  9,  3,  8,  8],
       [ 0, 10,  6, 18, 18],
       [15, 21, 18,  0, 12]])

In [87]:
ra_1.T

array([[8, 0, 5],
       [9, 5, 7],
       [3, 3, 6],
       [8, 9, 0],
       [8, 9, 4]], dtype=int32)

In [90]:
ra_6 = np.random.randint(10, size=(2,2,3))

In [91]:
ra_6

array([[[2, 4, 2],
        [4, 8, 4]],

       [[1, 8, 8],
        [5, 0, 8]]], dtype=int32)

In [92]:
ra_6.T

array([[[2, 1],
        [4, 5]],

       [[4, 8],
        [8, 0]],

       [[2, 8],
        [4, 8]]], dtype=int32)

### Dot product

In [97]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [98]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [99]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [101]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

In [102]:
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [109]:
mat3 = mat2.T

In [110]:
mat1.shape, mat3.shape

((5, 3), (3, 5))

In [111]:
np.dot(mat1, mat3)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

### Dot product example

In [113]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [115]:
# Weekly sales
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tue", "Wed", "Thu", "Fri"],
                            columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [117]:
# Prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [119]:
butter_prices = pd.DataFrame(prices.reshape(1,3),
                             index=["Price"],
                             columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [122]:
total_sales = np.dot(sales_amounts, prices)
total_sales

array([240, 138, 458, 232, 142])

In [123]:
weekly_sales["Total"] = total_sales
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total
Mon             12             15              0    240
Tue              3              3              7    138
Wed              9             19             18    458
Thu              4              6             12    232
Fri              1              6              7    142

## Example - IMAGES

<img src="images/numpy-panda.jpeg" width="500px"/>

In [126]:
# Turn an image into a NumPy array

from matplotlib.image import imread
panda = imread("images/numpy-panda.jpeg")
type(panda)

numpy.ndarray

In [127]:
panda.size, panda.shape, panda.ndim

(3271680, (852, 1280, 3), 3)

In [ ]:
# https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html
# https://jalammar.github.io/visual-numpy/
