# Introduction to Tensors

In [2]:
import datetime
print(f"Notebook last run: {datetime.datetime.now()}")

Notebook last run: 2025-05-27 09:31:33.977252


In [3]:
# Import TensoFlow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [4]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the number of dimensions of a tensor (ndim)
scalar.ndim

0

In [6]:
# Create a vector (1-D Tensor from a python list)
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
another_matix = tf.constant([
     [10.,7.],
     [3.,2.],
     [8.,9.]], dtype=tf.float16)
another_matix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

### Creating tensors with `tf.Variable`

In [11]:
changeable_tensor = tf.Variable([10,7], tf.int32)
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [12]:
changeable_tensor[0].assign(20)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([20,  7], dtype=int32)>

### Creating random tensors

In [13]:
random_g = tf.random.Generator.from_seed(42)
random_1 = random_g.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

### Shuffle the order of elements in a tensor

In [14]:
random_g = tf.random.Generator.from_seed(42)
random_2 = random_g.uniform(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [15]:
tf.random.set_seed(42)
tf.random.shuffle(random_2, seed=42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

### Other ways to make tensors

In [16]:
tf.ones([3, 10], dtype=tf.int32) # the main difference between tensors and NumPy arrays is that tensors can be run on GPUs.

<tf.Tensor: shape=(3, 10), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>

In [17]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [18]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [19]:
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [20]:
tf.size(A).numpy()

np.int32(24)

In [21]:
rank_2_tensor = tf.constant(np.arange(1, 10, dtype=np.int32), shape=(3, 3))
rank_2_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [22]:
# get last item of each of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9], dtype=int32)>

In [23]:
# ADD IN EXTRA DIMENSION
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]], dtype=int32)>

In [24]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]], dtype=int32)>

In [25]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [26]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(3, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]], dtype=int32)>

### Manipulating tensors

In [27]:
rank_2_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [28]:
tf.multiply(rank_2_tensor, 10)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]], dtype=int32)>

In [29]:
tf.subtract(rank_2_tensor, 5)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]], dtype=int32)>

**Matrix multiplication**

In [30]:
tf.linalg.matmul(rank_2_tensor, rank_2_tensor)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]], dtype=int32)>

In [31]:
mat1 = tf.constant(np.arange(1, 7, dtype=np.int32), shape=(2, 3))
mat2 = tf.constant(np.arange(7, 13, dtype=np.int32), shape=(2, 3))
mat1, mat2

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [32]:
tf.matmul(mat1, mat2, transpose_b=True)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  68],
       [122, 167]], dtype=int32)>

In [33]:
mat3 = tf.transpose(mat2)
mat3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]], dtype=int32)>

In [34]:
tf.matmul(mat1, mat3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  68],
       [122, 167]], dtype=int32)>

In [35]:
mat1, tf.reshape(mat1, shape=(3, 2)), tf.transpose(mat1)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 4],
        [2, 5],
        [3, 6]], dtype=int32)>)

In [36]:
tf.tensordot(mat1, mat3, axes=1) # the same as tf.matmul(mat1, mat3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  68],
       [122, 167]], dtype=int32)>

### Changing the datatype of a tensor

In [37]:
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [38]:
B = tf.cast(B, dtype=tf.float16)
B.dtype

tf.float16

In [39]:
C = tf.constant([1, 70])
C.dtype

tf.int32

In [40]:
C = tf.cast(C, dtype=tf.int16)
C.dtype

tf.int16

### Tensor aggregation

In [41]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([41, 65, 19, 54, 29, 39, 19, 53, 32, 91, 27, 35, 35, 31, 11,  8, 15,
       15, 18, 68, 44,  1, 47, 34, 24, 85, 43, 47, 69, 76, 28, 43, 68, 52,
       61, 39, 55, 60, 45, 97, 70, 54, 64, 36, 19, 71, 14, 39, 95, 34])>

In [42]:
tf.reduce_min(E), tf.reduce_max(E), tf.reduce_mean(E), tf.reduce_sum(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=97>,
 <tf.Tensor: shape=(), dtype=int64, numpy=44>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2219>)

In [43]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=534.5>

In [44]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=23.125>

In [45]:
mat1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [46]:
tf.math.reduce_prod(mat1)

<tf.Tensor: shape=(), dtype=int32, numpy=720>

In [47]:
1*2*3*4*5*6

720

### Find the positional min and max

In [48]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [49]:
tf.argmax(F) # index on our largest value position

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [50]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [51]:
tf.math.equal(F[tf.argmax(F)], tf.reduce_max(F))

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [52]:
tf.size(F)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [53]:
G = tf.reshape(F, shape=(10, 5))
G

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041],
       [0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686],
       [0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ],
       [0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ],
       [0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ],
       [0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
       [0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ],
       [0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ],
       [0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943],
       [0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]],
      dtype=float32)>

In [54]:
tf.argmax(G, axis=1)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 2, 1, 0, 0, 3, 0, 2, 2, 3])>

### Squeezing a tnesor (removing all single dimensions)

In [55]:
G_ext = tf.expand_dims(tf.expand_dims(G, axis=0), axis=0)
G_ext

<tf.Tensor: shape=(1, 1, 10, 5), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041],
         [0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686],
         [0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ],
         [0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ],
         [0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ],
         [0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
         [0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ],
         [0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ],
         [0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943],
         [0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [56]:
G_ext.shape

TensorShape([1, 1, 10, 5])

In [57]:
G_zqueezed = tf.squeeze(G_ext)
G_zqueezed

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041],
       [0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686],
       [0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ],
       [0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ],
       [0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ],
       [0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
       [0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ],
       [0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ],
       [0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943],
       [0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]],
      dtype=float32)>

### One-hot encoding tensors

In [58]:
indices_list = [0,1,2,3,4]
tf.one_hot(indices_list, depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [59]:
tf.one_hot(indices_list, depth=5, on_value="yes", off_value="no")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no', b'no'],
       [b'no', b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'no', b'yes', b'no'],
       [b'no', b'no', b'no', b'no', b'yes']], dtype=object)>

### Tensors and NumPy

In [60]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [61]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [62]:
#OR
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [63]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))  #tf.float64
tensor_J = tf.constant([3., 7., 10.]) #tf.float32
# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Check for GPU availability

In [64]:
print("GPU", "available" if tf.config.list_physical_devices("GPU") else "not available")

GPU available


In [65]:
!nvidia-smi

Tue May 27 09:31:41 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P0             27W /   70W |     106MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

# FCC TF 2.0

In [66]:
tensor1 = tf.ones([1, 2, 3])
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [67]:
tensor2 = tf.reshape(tensor1, [2, 3, 1])
tensor2

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [68]:
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells the tensor to calculate the size of the dimension in that place
tensor3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>